### ISSUE TITLE
Absence of pagination

### ISSUE THREAD

**Issue by efabioli** [KevinJump/Our.Umbraco.PublishQueue#5]
When PublishQueue table contains thousands of nodes, the absence of pagination allows to render all rows and this freezes the browser.

**Comment by KevinJump** [comment]
Indeed - almost like i didn't plan that bit properly :) 

quick fix (without writing stupid amount of pagination code) i might make it return the top 100 items only - does that make sense or do you **really** want pagination ?

**Comment by efabioli** [comment]
You may be right, I guess returning top N items is enough, as far as we have the total count at the top.

**Comment by KevinJump** [comment]
yep just pushed something that will only show top 100 (but the count is still the total) - will just check it's ok and push a new package out.

**Comment by KevinJump** [comment]
v1.0 has pagination now. shows 50 results per page. works much nicer when there are 1000's
